[project]
name = "booking-mate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "nltk>=3.9.1",
    "ruff>=0.8.6",
    "sqlalchemy>=2.0.36",
    "streamlit>=1.41.1",
    "streamlit-cookies-controller>=0.0.4",
]
